package:
  name: pkgbld
  version: 0.0.0

build:
  entry_points:
    - pbrelease = pkgbld.cli:main

requirements:
  build:
    - python
    - "conda>=4.5"
    - "conda-build>=3.5"
    - anaconda-client

  run:
    - python
    - "conda>=4.5"
    - "conda-build>=3.5"
    - anaconda-client

about:
  home: https://github.com/PSLmodels/Package-Builder
