package:
  name: pkgbld
  version: 0.0.0

build:
  entry_points:
    - pbrelease = pkgbld.cli:main

requirements:
  build:
    - python=3.6
    - "conda>=4.5"
    - "conda-build>=3.5"

  run:
    - python=3.6
    - "conda>=4.5"
    - "conda-build>=3.5"

test:
  imports:
    - pkgbld
  commands:
    - which pbrelease  # [unix]
    - where pbrelease  # [win]
    - pbrelease --help

about:
  home: https://github.com/PSLmodels/Package-Builder
