package:
  name: pkgbld
  version: 0.0.0

requirements:
  build:
    - python=3.6
    - "conda>=4.4.4"
    - conda-build

  run:
    - python=3.6
    - "conda>=4.4.4"
    - conda-build

test:
  imports:
    - pkgbld

about:
  home: https://github.com/open-source-economics/Package-Builder
